 import java.util.*;
 
public class Solution389 {
	/*
	 * 389. Find the Difference：
	 * Given two strings s and t which consist of only lowercase letters.
	 * String t is generated by random shuffling string s and then add one more letter at a random position.
	 * Find the letter that was added in t.
	 * 
	 * Input: s = "abcd", t = "abcde"
	 * Output: e
	 */
	
	
	  // My version: Runtime 10ms
	  public char findTheDifference(String s, String t){
		  int[] count = new int[26];
		  for(int i = 0; i < s.length(); i++){
			  count[s.charAt(i) - 'a']++;
		  }
		  
		  for(int i = 0; i < t.length(); i++){
			  count[t.charAt(i) - 'a']--;
		  }
		  
		  for(int i = 0; i < 26; i++){
			  if(count[i] != 0){
				  return (char)('a' + i);
			  }
		  }
		  return ' ';
	  }
	  
	  
	  // Genius Version! Runtime 7ms!
	  public char findTheDifference2(String s, String t){
		  /* As t.length() is just 1 character longer than s.length(), 
		   * we can use 1 pass to process both strings (20% better runtime performance)."
		   */
		  int charCode = t.charAt(s.length());
		  
		  for(int i = 0; i < s.length(); i++){
			  charCode -= (int) s.charAt(i);
			  charCode += (int) t.charAt(i);
		  }
		  
		  return (char)charCode;
	  }
	  
	  public static void main(String[] args){
		  String s = "abcd", t = "abcde";
		  Solution389 res = new Solution389();
		  System.out.println(res.findTheDifference(s, t));
	  }
}
